### ISSUE TITLE
Best practices regarding password authentication for a Web service

### ISSUE THREAD

**Issue by mkpankov** [breard-r/libreauth#30]
Hi. I'd like to ask some advice regarding the best way to use this library to implement password authentication for a Web service. I understand this might be out of scope of the project so please forgive me if I'm asking too much.

I'm using HTTPS to connect to server. My client is in Rust compiled to WASM, server is in Rust. There are several questions:

1. I've read that applying salt to hashed password is a good practice. How do I obtain this salt so that it would make sense 
from cryptography point of view? Doesn't look like I can pick any string of any length. Also, does it need to change? Should it be per user or per request? Should I apply it before or after hashing (since library has both)?
2. Do I transmit the password in plain text over HTTPS and hash it on the server? I've read conflicting arguments on this. I believe this is the correct way to hash password and store it in the database because otherwise I'm trusting client's code and the password hash itself becomes visible on the wire for any MITM attacker (hence becoming the password).
3. Example of doing password authentication has a case for password schema update. It says we should hash it again. Since we're not storing the original password, we should be doing a password reset procedure for the user, so that they can enter their old and new passwords, and we could hash new one and update the schema. Is that correct?

**Comment by breard-r** [comment]
Hi!

Could you ask those questions in the [discussions](https://github.com/breard-r/libreauth/discussions) section instead of issues please ? They could really be helpful to others and would be more accessible this way.

Meanwhile, I'm preparing some detailed answers :wink: 

PS: I know, some questions have already been answered in the issues, however that was before I activated GitHub's discussions section.

**Comment by mkpankov** [comment]
Migrated here https://github.com/breard-r/libreauth/discussions/31
