### ISSUE TITLE
Rust error API unnecessarily degraded to match C interface

### ISSUE THREAD

**Issue by OmegaJak** [breard-r/libreauth#51]
The current Rust return type for most methods in this crate looks something like `Result<_, ErrorCode>`. The `ErrorCode` enum includes types of errors that, as far as I can tell, are not possible when using this crate from Rust (`ErrorCode::Sucess`, `ErrorCode::NullPtr`, etc). This means that, when using this crate purely from Rust, to satisfy the Rust compiler, you must either resort to `unwrap()`/`expect()` or, if you pattern match the returned `Result`, you must match against error codes that are not possible.

Additionally, it would be nice if the returned errors gave relevant information - for example, for `PasswordTooShort`, return the actual length and the minimum length.

It looks to me like this was done primarily to support the usage of this crate through the C bindings -- this allows the exact same type to be returned from the Rust interface as it is from the C interface. However, we lose some of Rust's power in doing so. What I would love to see instead is a more idiomatic Rust error interface, which is mapped to the broader C error code interface inside the C bindings.

I'll be taking a stab at this for the `pass` module. This will mean a breaking API change, which I think is worth it in this case, but I'll understand if you don't think so.

Thanks for the great crate!

**Comment by breard-r** [comment]
Thank you, that's a nice thing to have.

I added an explicit `stderr` feature, activated by default, that activate the optional `thiserror` dependency. This is just in case some day a different crate is used.
