### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by drager** [breard-r/libreauth#56]
Hi!

Is it possible to get a new version (0.17.0) in the near future? I cannot upgrade reqwest to 0.12.x in my crates because of transitive dependency through libreauth. Latest master seems to have solved these issues.

**Comment by breard-r** [comment]
Sure. At first I was planning to wait to stabilize the use of the Balloon hashing function, but if the current state causes troubles I'm going to make a new release anyway, flagging Balloon support as experimental.

**Comment by breard-r** [comment]
I just released v0.17.0.

**Comment by drager** [comment]
Awesome, thanks a lot!
